
services:
  social-networkdb:
    image : mcr.microsoft.com/mssql/server:2025-latest

  seq:
   image: datalust/seq:latest

  api:
    image: ${DOCKER_REGISTRY-}sna-api
    build:
      context: backend
      dockerfile: src/sna-bootstrapper-api/Dockerfile

  frontend-angular:
    image: ${DOCKER_REGISTRY-}sna-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
  
  
