// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sna_infrastructure.Persistence;

#nullable disable

namespace sna_infrastructure.Migrations
{
    [DbContext(typeof(GraphVDbContext))]
    [Migration("20251231192920_EditEdgeKeys")]
    partial class EditEdgeKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sna_domain.Entities.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("sna_domain.Entities.Edge", b =>
                {
                    b.Property<Guid>("GraphId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NodeAId")
                        .HasColumnType("int");

                    b.Property<int>("NodeBId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasPrecision(4, 3)
                        .HasColumnType("float(4)");

                    b.HasKey("GraphId", "NodeAId", "NodeBId");

                    b.HasIndex("NodeAId");

                    b.HasIndex("NodeBId");

                    b.HasIndex("GraphId", "NodeAId", "NodeBId")
                        .IsUnique();

                    b.ToTable("Edges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Edges_NodeOrder", "[NodeAId] < [NodeBId]");
                        });
                });

            modelBuilder.Entity("sna_domain.Entities.Graph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Graphs");
                });

            modelBuilder.Entity("sna_domain.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("sna_domain.Entities.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Activity")
                        .HasColumnType("float");

                    b.Property<int>("Connections")
                        .HasColumnType("int");

                    b.Property<int>("DegreeCentrality")
                        .HasColumnType("int");

                    b.Property<Guid>("GraphId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Interaction")
                        .HasColumnType("int");

                    b.Property<decimal?>("NormalizedDegreeCentrality")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("sna_domain.Entities.Edge", b =>
                {
                    b.HasOne("sna_domain.Entities.Graph", "Graph")
                        .WithMany("Edges")
                        .HasForeignKey("GraphId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("sna_domain.Entities.Node", "NodeA")
                        .WithMany()
                        .HasForeignKey("NodeAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sna_domain.Entities.Node", "NodeB")
                        .WithMany()
                        .HasForeignKey("NodeBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Graph");

                    b.Navigation("NodeA");

                    b.Navigation("NodeB");
                });

            modelBuilder.Entity("sna_domain.Entities.Node", b =>
                {
                    b.HasOne("sna_domain.Entities.Graph", "Graph")
                        .WithMany("Nodes")
                        .HasForeignKey("GraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("sna_domain.Entities.Graph", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
